In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load



import numpy as np # linear algebra

#Import Numpy

# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory



In [2]:
score = np.loadtxt('/survey-Data-User.txt', dtype = int)
#Load Survey data and convert it into int data type and store it to variable 'score'
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [3]:
score.ndim #it will provide the dimension of an array


1

In [4]:
score.shape #It will return the no.of elements in the each dimension


(1459,)

In [5]:
score.dtype #Type of the data (integer, float, Python object, etc.)


dtype('int64')

In [6]:
np.min(score), np.max(score), round(np.mean(score), 2) #Min, Max and Mean..etc


(1, 10, 7.29)

In [7]:
# nps = %promoters - %detractors
#NPS Formula

In [8]:
score <= 6 # detractors condition

array([False, False,  True, ...,  True, False, False])

In [9]:
score >= 9  #promoters condition

array([False,  True, False, ..., False,  True,  True])

In [10]:
# Get Len of Promoters & Detracters
nuof_promoters = len(score[score >= 9 ])
nuof_detracters = len(score[score <= 6])

In [11]:
total_responses = score.shape[0] # total number of responses
total_responses

1459

In [12]:
percof_promoters = (nuof_promoters/total_responses)*100
percof_promoters #% Of Promoters

52.0904729266621

In [13]:
percof_detracters = (nuof_detracters/total_responses)*100
percof_detracters #% Of Detracters

28.30705962988348

In [14]:
nps = percof_promoters - percof_detracters
nps #NPS Score  - 23.783413296778622

23.783413296778622

In [15]:
round(nps, 2) #Round Fun()  - 23.78%

23.78

In [16]:
#I hope you find these resources helpful:)